"""create yellow taxi trips table

Revision ID: 70630161b925
Revises: 
Create Date: 2026-07-28 19:40:32.942127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70630161b925'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yellow_taxi_trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('tpep_pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('tpep_dropoff_datetime', sa.DateTime(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_hour', sa.Integer(), nullable=False),
    sa.Column('pickup_day_name', sa.String(length=9), nullable=False),
    sa.Column('trip_duration_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('trip_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fare_per_mile', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ratecode_id', sa.Integer(), nullable=True),
    sa.Column('store_and_fwd_flag', sa.String(length=1), nullable=True),
    sa.Column('pu_location_id', sa.Integer(), nullable=False),
    sa.Column('do_location_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Integer(), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mta_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tolls_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('improvement_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('congestion_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('airport_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cbd_congestion_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yellow_taxi_trips')
    # ### end Alembic commands ###
